replicaCount: 1
appName: 'appname'
namespace: 'namespace'
environment: 'environment'
    
readinessProbe:
  httpGet:
    path: /health
    port: 5000
  initialDelaySeconds: 1
  periodSeconds: 20
  timeoutSeconds: 10
  successThreshold: 1
  failureThreshold: 6

livenessProbe:
  httpGet:
    path: /health
    port: 5000
  initialDelaySeconds: 1
  periodSeconds: 20
  timeoutSeconds: 10
  successThreshold: 1
  failureThreshold: 2

resources:
  limits:
    cpu: 500m
    memory: 256Mi
  requests:
    cpu: 10m
    memory: 8Mi
    
image:
  repository: registry.tools.local.com.br/<+stage.variables.FOCUS_AREA>/<+stage.variables.NAME_PROJECT>
  tag: <+stage.variables.BRANCH_PIPELINE>-<+stage.variables.SEQUENCE_PIPELINE>
  pullPolicy: IfNotPresent
  imagePullSecret: "proget"
  ports:
    - name: http
      containerPort: 5000
      protocol: TCP
    - name: https
      containerPort: 5001
      protocol: TCP
      
service:
  type: ClusterIP
  port: 5000
  targetPort: http
  portName: http
  protocol: TCP

ingress:
  enabled: "true"
  host: <+pipeline.stages.Deploy.spec.infrastructure.infrastructureDefinition.provisioner.steps.SetClusterDynamic.output.outputVariables.urlIngress>