replicaCount: 1
appName: dotnet-cronjob
namespace: apps
environment: teste-ewerton

parallelism: 1
productionParallelism: 10
completions: 1
productionCompletions: 10
activeDeadlineSeconds: 36000
schedule: '* * * * *'
concurrencyPolicy: Allow
failedJobsHistoryLimit: 30
successfulJobsHistoryLimit: 30
startingDeadlineSeconds: 200

resources:
  limits:
    cpu: 500m
    memory: 384Mi
  requests:
    cpu: 24m
    memory: 64Mi

image:
  repository: ewertonmarschalk/dotnet-api
  tag: 1.0.1
  pullPolicy: IfNotPresent