containerPlataform: rancher
replicaCount: 2

appName: "java-api"
namespace: "appoena"
environment: "production"

resources:
  limits:
    cpu: 250m
    memory: 256Mi
  requests:
    cpu: 1m
    memory: 64Mi

image:
  repository: "ewertonmarschalk/java-api"
  tag: 1.0.1
  pullPolicy: IfNotPresent
  ports:
    - name: http
      containerPort: 8080
      protocol: TCP
      
service:
  type: ClusterIP
  port: 8080
  targetPort: http
  portName: http
  protocol: TCP

ingress:
  enabled: true
  host: "javaapi.cluster.local"
  cert: apps-cert-tls
