apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Values.appName }} 
  labels:
    app: {{ .Values.appName }} 
    deploymentconfig: {{ .Values.appName }} 
    kube_app: {{ .Values.appName }} 
    kube_deployment: {{ .Values.appName }} 
    kube_namespace: {{ .Values.namespace }}
    tags.datadoghq.com/env: {{ .Values.environment }}
    tags.datadoghq.com/service: {{ .Values.appName }}
    tags.datadoghq.com/version: {{ .Values.image.tag }}
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      app: {{ .Values.appName }} 
      deploymentconfig: {{ .Values.appName }} 
      kube_app: {{ .Values.appName }} 
      kube_deployment: {{ .Values.appName }} 
      kube_namespace: {{ .Values.namespace }}
  template:
    metadata:
      annotations:
        "ad.datadoghq.com/{{ .Values.appName }}.logs" : '[{"source":"dotnet"}]'
        admission.datadoghq.com/dotnet-lib.version: v2.35.0
      labels:
        app: {{ .Values.appName }} 
        deploymentconfig: {{ .Values.appName }} 
        kube_app: {{ .Values.appName }} 
        kube_deployment: {{ .Values.appName }} 
        kube_namespace: {{ .Values.namespace }}
        tags.datadoghq.com/env: {{ .Values.environment }}
        tags.datadoghq.com/service: {{ .Values.appName }}
        tags.datadoghq.com/version: {{ .Values.image.tag }}
        admission.datadoghq.com/enabled: "true"
    spec:    
      containers:
        - name: {{ .Values.appName }}
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}         
          {{- with .Values.image.ports }}
          ports:
            {{- toYaml . | nindent 12 }}
          {{- end }}
          resources:
            {{- toYaml .Values.resources | nindent 12 }}     
          env:
          - name: DD_LOGS_INJECTION
            value: "true"
          - name: DD_APPSEC_ENABLED
            value: "true"
          - name: DD_RUNTIME_METRICS_ENABLED
            value: "true"
