apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.appName }}
  labels:
    app: {{ .Values.appName }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.service.port }}
      targetPort: {{ .Values.service.targetPort }}
      protocol: {{ .Values.service.protocol }}
      name: {{ .Values.service.portName }}
    {{- if (eq .Values.appName "app-havan-identity-server") }}   
    - port: 5001
      targetPort: https
      protocol: TCP
      name: https
    {{- end }} 
  selector:
    app: {{ .Values.appName }}
    deploymentconfig: {{ .Values.appName }}
    kube_app: {{ .Values.appName }}
    kube_deployment: {{ .Values.appName }}
    kube_namespace: {{ .Values.namespace }}

