containerPlataform: rancher
replicaCount: 2

appName: "dotnet-api"
namespace: "appoena"
environment: "production"


resources:
  limits:
    cpu: 250m
    memory: 256Mi
  requests:
    cpu: 1m
    memory: 64Mi

image:
  repository: "ewertonmarschalk/dotnet-api"
  tag: 1.0.1
  pullPolicy: IfNotPresent
  ports:
    - name: http
      containerPort: 80
      protocol: TCP
      
service:
  type: ClusterIP
  port: 80
  targetPort: http
  portName: http
  protocol: TCP

ingress:
  enabled: true
  host: "dotnetapi.local"
  cert: apps-cert-tls
