{{- if and (eq .Values.hpa.status "byMetrics") (eq .Values.appName "havan-portal-cliente") (eq .Values.environment "production") }}
apiVersion: autoscaling/v2beta2
kind: HorizontalPodAutoscaler
metadata:
  name: {{ .Values.appName }}
  namespace: {{ .Values.namespace }}
spec:
  metrics:
  - resource:
      name: cpu
      target:
        averageValue: 400m
        type: AverageValue
    type: Resource
  maxReplicas: 20 #{{ .Values.hpa.replicaCount.max }}
  minReplicas: 10 #{{ .Values.hpa.replicaCount.min }}
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: {{ .Values.appName }}
{{- end }}
