replicaCount: 1
appName: 'appname'
namespace: 'namespace'
environment: 'environment'
areaFoco: "Cliente"
deployment_strategy: 'deployment strategy'

hpa:
  status: "status"
  replicaCount:
    min: 1
    max: 10
  metric:
    targetAverageValue: 1.2
    metricName: "metrics"   

resources:
  limits:
    cpu: 500m
    memory: 256Mi
  requests:
    cpu: 10m
    memory: 8Mi
    
image:
  repository: repository
  tag: tag
  pullPolicy: IfNotPresent
  imagePullSecret: "proget"
  ports:
    - name: http
      containerPort: 8080
      protocol: TCP
      
service:
  type: ClusterIP
  port: 8080
  targetPort: http
  portName: http
  protocol: TCP

ingress:
  enabled: "true"
  host: url