containerPlataform: rancher
replicaCount: 2

appName: "python-api"
namespace: "appoena"
environment: "production"

resources:
  limits:
    cpu: 250m
    memory: 256Mi
  requests:
    cpu: 1m
    memory: 64Mi

image:
  repository: "ewertonmarschalk/python-api"
  tag: 1.0.2
  pullPolicy: IfNotPresent
  ports:
    - name: http
      containerPort: 5000
      protocol: TCP
      
service:
  type: ClusterIP
  port: 5000
  targetPort: http
  portName: http
  protocol: TCP

ingress:
  enabled: true
  host: "pythonapi.cluster.local"
